# .github/FUNDING.yml

github: [syeda7]  
patreon: syeda7  
open_collective: student-open-projects  
ko_fi: syeda7  
tidelift: npm/student-management-system 
community_bridge: tech4good  
liberapay: syeda_dev  
issuehunt: syeda7  
lfx_crowdfunding: abedi-academy  
polar: syeda7  
buy_me_a_coffee: syeda7  
thanks_dev: syeda7  
custom: ['https://www.linkedin.com/in/uzra-fatima-syeda-034976192/']
